#!/bin/bash
#SBATCH -p short
#SBATCH -t 0-01:00
#SBATCH -c 8
#SBATCH --mem=80G
#SBATCH --array=1-200
#SBATCH -o hostname.%j.out 
#SBATCH -e hostname.%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=pnaderiy@bidmc.harvard.edu




module load gcc/6.2.0 R/3.6.1

#module load mpi/openmi/2.1.1/gcc-6.2

#Number of cores
cores=8

# Inputs

# Select genesets file
gs="KEGG_PCxN.RDS"

# Select desired relationships based on the table (github)
# Example: rels="1,2,4,6"
rels="11"

# Select whether you want partial-correlation(0) or not(1)
pcor="0"

# Output folder
ofo="output_KEGG_PCxN"

# Run code (no need to change that) 

Rscript mir_estimates02.R $SLURM_ARRAY_TASK_ID $gs $cores $ofo
echo estimates02 $SLURM_ARRAY_TASK_ID done !!!

# Aggregating the 2 matrices
# Rscript PCxN_estimates03.R $gs $ofo
# echo estimates03 done !!!

echo PCxN Complete !!!
